#!/usr/bin/env zsh

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/, /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd

pushd $DOTFILES/work/*/
for folder in $DOTFILES/work/*/; then
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd
